# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Student Name
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [1]:
# 1.1 Import Packages
from pathlib import Path 
import pandas as pd

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [32]:
# 1.2 Set project folders using relative paths
project_fldr = Path.cwd().parent
raw_fldr = project_fldr / 'data' / 'raw'
processed_fldr = project_fldr / 'data' / 'processed'

print(project_fldr)
print(raw_fldr)
print(processed_fldr)

/Users/matthewswire/Desktop/Duke/Fall_2026/Data_Exploration/ENV700
/Users/matthewswire/Desktop/Duke/Fall_2026/Data_Exploration/ENV700/data/raw
/Users/matthewswire/Desktop/Duke/Fall_2026/Data_Exploration/ENV700/data/processed

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [33]:
# 1.3 Create file path variables

ozone_2024 = pd.read_csv(raw_fldr / 'EPAair_O3_NC2024_raw.csv')
ozone_2025 = pd.read_csv(raw_fldr / 'EPAair_O3_NC2025_raw.csv')
pm_2024 = pd.read_csv(raw_fldr / 'EPAair_PM25_NC2024_raw.csv')
pm_2025 = pd.read_csv(raw_fldr / 'EPAair_PM25_NC2025_raw.csv')

In [34]:
pm_2024.info() # to see variable names and info

<class 'pandas.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            9752 non-null   str
 1   Source                          9752 non-null   str
 2   Site ID                         9752 non-null   int64
 3   POC                             9752 non-null   int64
 4   Daily Mean PM2.5 Concentration  9752 non-null   float64
 5   Units                           9752 non-null   str
 6   Daily AQI Value                 9752 non-null   int64
 7   Local Site Name                 9752 non-null   str
 8   Daily Obs Count                 9752 non-null   int64
 9   Percent Complete                9752 non-null   float64
 10  AQS Parameter Code              9752 non-null   int64
 11  AQS Parameter Description       9752 non-null   str
 12  Method Code                     9752 non-null   int64
 13  Method Description              9752 non-null   str
 14  CBSA Code                       8391 non-null   float64
 15  CBSA Name                       8391 non-null   str
 16  State FIPS Code                 9752 non-null   int64
 17  State                           9752 non-null   str
 18  County FIPS Code                9752 non-null   int64
 19  County                          9752 non-null   str
 20  Site Latitude                   9752 non-null   float64
 21  Site Longitude                  9752 non-null   float64
dtypes: float64(5), int64(8), str(9)
memory usage: 1.6 MB

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [55]:
# 1.4 Read data into dataframes
ozone_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 9519 entries, 0 to 9518
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Date                                  9519 non-null   datetime64[us]
 1   Source                                9519 non-null   str
 2   Site ID                               9519 non-null   int64
 3   POC                                   9519 non-null   int64
 4   Daily Max 8-hour Ozone Concentration  9519 non-null   float64
 5   Units                                 9519 non-null   str
 6   Daily AQI Value                       9519 non-null   int64
 7   Local Site Name                       9519 non-null   str
 8   Daily Obs Count                       9519 non-null   int64
 9   Percent Complete                      9519 non-null   float64
 10  AQS Parameter Code                    9519 non-null   int64
 11  AQS Parameter Description             9519 non-null   str
 12  Method Code                           9519 non-null   int64
 13  CBSA Code                             7294 non-null   float64
 14  CBSA Name                             7294 non-null   str
 15  State FIPS Code                       9519 non-null   int64
 16  State                                 9519 non-null   str
 17  County FIPS Code                      9519 non-null   int64
 18  County                                9519 non-null   str
 19  Site Latitude                         9519 non-null   float64
 20  Site Longitude                        9519 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(8), str(7)
memory usage: 1.5 MB

In [37]:
#ozone_2024.info()

ozone_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 9519 entries, 0 to 9518
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Date                                  9519 non-null   str
 1   Source                                9519 non-null   str
 2   Site ID                               9519 non-null   int64
 3   POC                                   9519 non-null   int64
 4   Daily Max 8-hour Ozone Concentration  9519 non-null   float64
 5   Units                                 9519 non-null   str
 6   Daily AQI Value                       9519 non-null   int64
 7   Local Site Name                       9519 non-null   str
 8   Daily Obs Count                       9519 non-null   int64
 9   Percent Complete                      9519 non-null   float64
 10  AQS Parameter Code                    9519 non-null   int64
 11  AQS Parameter Description             9519 non-null   str
 12  Method Code                           9519 non-null   int64
 13  CBSA Code                             7294 non-null   float64
 14  CBSA Name                             7294 non-null   str
 15  State FIPS Code                       9519 non-null   int64
 16  State                                 9519 non-null   str
 17  County FIPS Code                      9519 non-null   int64
 18  County                                9519 non-null   str
 19  Site Latitude                         9519 non-null   float64
 20  Site Longitude                        9519 non-null   float64
dtypes: float64(5), int64(8), str(8)
memory usage: 1.5 MB

In [32]:
pm_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            9752 non-null   str
 1   Source                          9752 non-null   str
 2   Site ID                         9752 non-null   int64
 3   POC                             9752 non-null   int64
 4   Daily Mean PM2.5 Concentration  9752 non-null   float64
 5   Units                           9752 non-null   str
 6   Daily AQI Value                 9752 non-null   int64
 7   Local Site Name                 9752 non-null   str
 8   Daily Obs Count                 9752 non-null   int64
 9   Percent Complete                9752 non-null   float64
 10  AQS Parameter Code              9752 non-null   int64
 11  AQS Parameter Description       9752 non-null   str
 12  Method Code                     9752 non-null   int64
 13  Method Description              9752 non-null   str
 14  CBSA Code                       8391 non-null   float64
 15  CBSA Name                       8391 non-null   str
 16  State FIPS Code                 9752 non-null   int64
 17  State                           9752 non-null   str
 18  County FIPS Code                9752 non-null   int64
 19  County                          9752 non-null   str
 20  Site Latitude                   9752 non-null   float64
 21  Site Longitude                  9752 non-null   float64
dtypes: float64(5), int64(8), str(9)
memory usage: 1.6 MB

In [ ]:
pm_2025.info()

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,Units,Daily AQI Value,Local Site Name,Daily Obs Count,Percent Complete,...,Method Code,Method Description,CBSA Code,CBSA Name,State FIPS Code,State,County FIPS Code,County,Site Latitude,Site Longitude
0,1/1/25,AQS,370110002,1,0.7,ug/m3 LC,4,Linville Falls,1,100,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
1,1/4/25,AQS,370110002,1,1.2,ug/m3 LC,7,Linville Falls,1,100,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
2,1/7/25,AQS,370110002,1,1.5,ug/m3 LC,8,Linville Falls,1,100,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
3,1/10/25,AQS,370110002,1,4.2,ug/m3 LC,23,Linville Falls,1,100,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
4,1/13/25,AQS,370110002,1,5.0,ug/m3 LC,28,Linville Falls,1,100,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [ ]:
# 1.5 Report the dimensions of each dataset
ozone_2025.shape

(9466, 21)

In [29]:
ozone_2024.shape

(9519, 21)

In [28]:
pm_2024.shape

(9752, 22)

In [30]:
pm_2025.shape

(10184, 22)

---
### 2. Wrangle individual datasets

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [38]:
# Convert the Date column to DateTime objects
ozone_2024['Date'] = pd.to_datetime(ozone_2024['Date'],format='%m/%d/%Y')
ozone_2025['Date'] = pd.to_datetime(ozone_2025['Date'],format='%m/%d/%Y')
pm_2024['Date'] = pd.to_datetime(pm_2024['Date'],format='%m/%d/%Y')
pm_2025['Date'] = pd.to_datetime(pm_2025['Date'],format='%m/%d/%y')


# Print date ranges
print('Ozone 2024 date range:',ozone_2024['Date'].min(),'-',ozone_2024['Date'].max())
print('Ozone 2025 date range:',ozone_2025['Date'].min(),'-',ozone_2025['Date'].max())
print('PM25 2024 date range:',pm_2024['Date'].min(),'-',pm_2024['Date'].max())
print('PM25 2025 date range:',pm_2025['Date'].min(),'-',pm_2025['Date'].max())

Ozone 2024 date range: 2024-01-01 00:00:00 - 2024-12-30 00:00:00
Ozone 2025 date range: 2025-01-01 00:00:00 - 2025-12-31 00:00:00
PM25 2024 date range: 2024-01-01 00:00:00 - 2024-12-31 00:00:00
PM25 2025 date range: 2025-01-01 00:00:00 - 2025-12-31 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [44]:
# 2.2 Subset columns
core_cols = ['Date','Daily AQI Value','Local Site Name','AQS Parameter Description','County','Site Latitude','Site Longitude']

ozone_2024_clean = ozone_2024[core_cols]
ozone_2025_clean = ozone_2025[core_cols]
pm_2024_clean= pm_2024[core_cols]
pm_2025_clean= pm_2025[core_cols]

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [45]:
# 2.3 Update values
pm_2024_clean ['AQS Parameter Description'] = 'PM2.5'
pm_2025_clean ['AQS Parameter Description'] = 'PM2.5'

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [46]:
ozone_2024_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9519 entries, 0 to 9518
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       9519 non-null   datetime64[us]
 1   Daily AQI Value            9519 non-null   int64
 2   Local Site Name            9519 non-null   str
 3   AQS Parameter Description  9519 non-null   str
 4   County                     9519 non-null   str
 5   Site Latitude              9519 non-null   float64
 6   Site Longitude             9519 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 520.7 KB

In [47]:
ozone_2025_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9466 entries, 0 to 9465
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       9466 non-null   datetime64[us]
 1   Daily AQI Value            9466 non-null   int64
 2   Local Site Name            9466 non-null   str
 3   AQS Parameter Description  9466 non-null   str
 4   County                     9466 non-null   str
 5   Site Latitude              9466 non-null   float64
 6   Site Longitude             9466 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 517.8 KB

In [24]:
pm_2024_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       9752 non-null   datetime64[us]
 1   Daily AQI Value            9752 non-null   int64
 2   Local Site Name            9752 non-null   str
 3   AQS Parameter Description  9752 non-null   str
 4   County                     9752 non-null   str
 5   Site Latitude              9752 non-null   float64
 6   Site Longitude             9752 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 533.4 KB

In [25]:
pm_2025_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 10184 entries, 0 to 10183
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       10184 non-null  datetime64[us]
 1   Daily AQI Value            10184 non-null  int64
 2   Local Site Name            10184 non-null  str
 3   AQS Parameter Description  10184 non-null  str
 4   County                     10184 non-null  str
 5   Site Latitude              10184 non-null  float64
 6   Site Longitude             10184 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 557.1 KB

**Check**

Went to use .info command to ensure the filtered colums and 'Date' was in proper datetime64 format

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [48]:
# 3.2 Concatentate & report shape

combined_ozone_pm = pd.concat([ozone_2024_clean,ozone_2025_clean,pm_2024_clean,pm_2025_clean])

combined_ozone_pm.shape

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [49]:
# 3.3 View a sample of data
combined_ozone_pm.sample(10,random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
7936,2024-07-20,24,Pitt Agri. Center,PM2.5,Pitt,35.641276,-77.360126
6483,2024-04-22,40,University Meadows,Ozone,Mecklenburg,35.314158,-80.713469
5578,2025-02-18,53,Remount,PM2.5,Mecklenburg,35.213171,-80.874084
2975,2025-08-08,39,Clemmons Middle,Ozone,Forsyth,36.026612,-80.341962
8796,2024-01-08,12,Old High School,PM2.5,Swain,35.498711,-83.310242
4104,2024-08-26,59,Mendenhall School,PM2.5,Guilford,36.109006,-79.802314
6287,2025-02-16,27,Spruce Pine Hospital,PM2.5,Mitchell,35.912487,-82.062082
1157,2024-08-14,40,Beaufort,Ozone,Carteret,34.884800,-76.620300
4178,2024-09-14,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625
4073,2025-03-29,45,Waynesville School,Ozone,Haywood,35.507224,-82.963625

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [72]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
sites_oz24 = set(ozone_2024_clean['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
sites_oz25 = set(ozone_2025_clean['Local Site Name'])
sites_pm24 = set(pm_2024_clean['Local Site Name'])
sites_pm25 = set(pm25_2025_clean['Local Site Name'])
## Compute the intersection 
common_sites = sites_oz24 & sites_oz25 & sites_pm24 & sites_pm25
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [68]:
# 4.1 Subset for records with sites in common
selected_sites = ['Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.']

common_sites_subset = (
    combined_ozone_pm
    .loc[lambda df: df['Local Site Name'].isin(selected_sites)]
    .reset_index()
)

common_sites_subset.head()

,index,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
0,245,2024-03-01,31,Linville Falls,Ozone,Avery,35.972347,-81.933072
1,246,2024-03-02,37,Linville Falls,Ozone,Avery,35.972347,-81.933072
2,247,2024-03-03,38,Linville Falls,Ozone,Avery,35.972347,-81.933072
3,248,2024-03-04,36,Linville Falls,Ozone,Avery,35.972347,-81.933072
4,249,2024-03-05,43,Linville Falls,Ozone,Avery,35.972347,-81.933072

In [69]:
combined_ozone_pm.head()

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
0,2024-03-01,26,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
1,2024-03-02,34,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
2,2024-03-03,35,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
3,2024-03-04,37,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
4,2024-03-05,42,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [83]:
# 4.2 Group and summarize data, then report its dimensions

pollutants_summary = (
    common_sites_subset
    .groupby(['Date','Local Site Name','AQS Parameter Description','County'])
    .agg(
        mean_daily_AQI = ('Daily AQI Value','mean'),
        mean_lat = ('Site Latitude','mean'),
        mean_long = ('Site Longitude','mean')
    )
    .reset_index()
)

pollutants_summary.shape

(17017, 7)

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [ ]:
# 4.3 Calculate year and month columns
pollutants_summary['year']=pollutants_summary['Date'].dt.year
pollutants_summary['month']=pollutants_summary['Date'].dt.month

In [89]:
pollutants_summary.head()

,Date,Local Site Name,AQS Parameter Description,County,mean_daily_AQI,mean_lat,mean_long,year,month
0,2024-01-01,Bryson City,PM2.5,Swain,43.0,35.434767,-83.442133,2024,1
1,2024-01-01,Castle Hayne,PM2.5,New Hanover,44.5,34.364167,-77.838611,2024,1
2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,47.5,36.026612,-80.341962,2024,1
3,2024-01-01,Durham Armory,PM2.5,Durham,61.0,36.032955,-78.904037,2024,1
4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,14.0,35.379167,-82.792500,2024,1

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [96]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns
pollutants_summary_wide = (
    pollutants_summary
    .pivot_table(
        index=['Local Site Name','Date','County'],
        columns='AQS Parameter Description',
        values= 'mean_daily_AQI'
    )
    .reset_index()
)

pollutants_summary_wide.sample(10,random_state=42)

AQS Parameter Description,Local Site Name,Date,County,Ozone,PM2.5
3872,Garinger High School,2025-02-24,Mecklenburg,50.0,66.0
3126,Frying Pan Mountain,2024-09-12,Haywood,42.0,26.0
6386,Mendenhall School,2024-09-15,Guilford,25.0,34.0
9421,Rockwell,2025-12-09,Rowan,25.0,37.0
5974,Linville Falls,2025-05-18,Avery,47.0,NaN
1691,Clemmons Middle,2024-08-22,Forsyth,48.0,47.0
8087,Pitt Agri. Center,2024-03-30,Pitt,54.0,46.0
9862,West Johnston Co.,2025-02-23,Johnston,NaN,47.0
713,Bryson City,2025-12-16,Swain,NaN,55.0
6343,Mendenhall School,2024-08-03,Guilford,34.0,59.0

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [98]:
# 5.1 Save the file

pollutants_summary_wide.to_csv(
    project_fldr/'A4_Wrangling_synthesized_data',
    index=False
)

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [103]:
pollutants_summary_wide.head()

AQS Parameter Description Local Site Name       Date County  Ozone  PM2.5
0                             Bryson City 2024-01-01  Swain    NaN   43.0
1                             Bryson City 2024-01-02  Swain    NaN   21.0
2                             Bryson City 2024-01-03  Swain    NaN   34.0
3                             Bryson City 2024-01-04  Swain    NaN   31.0
4                             Bryson City 2024-01-05  Swain    NaN   45.0

In [107]:
# 6.1 Generate a summary table and show its first 5 records

pollutants_summary_table = (
    pollutants_summary_wide
    .assign(
        year=lambda df: df['Date'].dt.year,
        month=lambda df: df['Date'].dt.month
    )
    .groupby(['Local Site Name','year','month'])
    .agg(
        mean_ozone= ('Ozone','mean'),
        mean_pm25 = ('PM2.5','mean')
    )
    .reset_index()
)

pollutants_summary_table.head()

  Local Site Name  year  month  mean_ozone  mean_pm25
0     Bryson City  2024      1         NaN  22.580645
1     Bryson City  2024      2         NaN  32.000000
2     Bryson City  2024      3   40.709677  30.935484
3     Bryson City  2024      4   43.793103  36.066667
4     Bryson City  2024      5   37.419355  30.387097

In [110]:
pollutants_summary_table.sample(10,random_state=42) # check to see how the data is across random sample

          Local Site Name  year  month  mean_ozone  mean_pm25
222     Mendenhall School  2024     10   38.096774  40.307692
42           Castle Hayne  2025      7   29.096774  34.467742
291     Pitt Agri. Center  2024      7   35.161290  36.193548
300     Pitt Agri. Center  2025      4   40.366667  32.300000
56        Clemmons Middle  2024      9   36.300000  33.450000
335     West Johnston Co.  2024      3   41.548387  35.870968
15            Bryson City  2025      4   43.433333  35.966667
57        Clemmons Middle  2024     10   37.833333  39.258065
245      Millbrook School  2024      9   32.733333  39.600000
124  Garinger High School  2024      6   53.033333  44.933333

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.